name: pmsn20232
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  chewie: ^1.7.1
  concentric_transition: ^1.0.3
  day_night_switcher: ^0.2.0+1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^16.1.0
  flutter_rating_bar: ^4.0.1
  flutter_rating_native: ^0.0.2
  flutter_slidable: ^3.0.0
  fluttertoast: ^8.2.2
  http: ^1.1.0
  intl: ^0.18.1
  lottie: ^2.6.0
  path_provider: ^2.1.1
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  sqflite: ^2.3.0
  table_calendar: ^3.0.9
  timezone: ^0.9.2
  video_player: ^2.7.2
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/.
    - assets/images/.
    - assets/animations/.
